import * as React from 'react';
import { SomeWrapper, ExtendWrapper } from '../wrappers/Wrapper';
import { ValidationProps } from '../_shared/hooks/useValidation';
import { ExportedDateRangePickerViewProps } from './DateRangePickerView';
import { ExportedDateRangePickerInputProps } from './DateRangePickerInput';
import { DateRange as DateRangeType, RangeInput } from './RangeTypes';
import { DateRangeValidationError } from '../_helpers/date-utils';
export interface BaseDateRangePickerProps extends ExportedDateRangePickerViewProps, ValidationProps<DateRangeValidationError, RangeInput>, ExportedDateRangePickerInputProps {
    /**
     * Text for start input label and toolbar placeholder
     * @default "Start"
     */
    startText?: React.ReactNode;
    /**
     * Text for end input label and toolbar placeholder
     * @default "end"
     */
    endText?: React.ReactNode;
}
export declare const useDateRangeValidation: (value: RangeInput, props: BaseDateRangePickerProps) => DateRangeValidationError;
export declare function makeRangePicker<TWrapper extends SomeWrapper>(name: string, Wrapper: TWrapper): React.ForwardRefExoticComponent<React.PropsWithoutRef<BaseDateRangePickerProps & Pick<import("../Picker/SharedPickerProps").AllSharedPickerProps<RangeInput, DateRangeType>, "label" | "mask" | "dateAdapter" | "value" | "className" | "onChange" | "open" | "disabled" | "orientation" | "readOnly" | "toolbarFormat" | "toolbarPlaceholder" | "toolbarTitle" | "InputProps" | "inputFormat" | "ignoreInvalidInputs" | "openPickerIcon" | "acceptRegex" | "InputAdornmentProps" | "OpenPickerButtonProps" | "rifmFormatter" | "disableOpenPicker" | "disableMaskedInput" | "getOpenDialogAriaText" | "onClose" | "onAccept" | "autoOk" | "onOpen" | "showToolbar" | "ToolbarComponent"> & ExportedDateRangePickerInputProps & ExtendWrapper<TWrapper>> & React.RefAttributes<HTMLDivElement>>;
export declare type DateRange = DateRangeType;
export declare const DateRangePicker: React.ForwardRefExoticComponent<BaseDateRangePickerProps & Pick<import("../Picker/SharedPickerProps").AllSharedPickerProps<RangeInput, DateRangeType>, "label" | "mask" | "dateAdapter" | "value" | "className" | "onChange" | "open" | "disabled" | "orientation" | "readOnly" | "toolbarFormat" | "toolbarPlaceholder" | "toolbarTitle" | "InputProps" | "inputFormat" | "ignoreInvalidInputs" | "openPickerIcon" | "acceptRegex" | "InputAdornmentProps" | "OpenPickerButtonProps" | "rifmFormatter" | "disableOpenPicker" | "disableMaskedInput" | "getOpenDialogAriaText" | "onClose" | "onAccept" | "autoOk" | "onOpen" | "showToolbar" | "ToolbarComponent"> & ExportedDateRangePickerInputProps & Pick<import("../wrappers/ResponsiveWrapper").ResponsiveWrapperProps, "displayStaticWrapperAs" | "DialogProps" | "okText" | "cancelText" | "clearText" | "todayText" | "clearable" | "showTodayButton" | "showTabs" | "wider" | "PopoverProps" | "PopperProps" | "TransitionComponent" | "desktopModeMediaQuery"> & React.RefAttributes<HTMLDivElement>>;
export declare type DateRangePickerProps = React.ComponentProps<typeof DateRangePicker>;
export declare const DesktopDateRangePicker: React.ForwardRefExoticComponent<BaseDateRangePickerProps & Pick<import("../Picker/SharedPickerProps").AllSharedPickerProps<RangeInput, DateRangeType>, "label" | "mask" | "dateAdapter" | "value" | "className" | "onChange" | "open" | "disabled" | "orientation" | "readOnly" | "toolbarFormat" | "toolbarPlaceholder" | "toolbarTitle" | "InputProps" | "inputFormat" | "ignoreInvalidInputs" | "openPickerIcon" | "acceptRegex" | "InputAdornmentProps" | "OpenPickerButtonProps" | "rifmFormatter" | "disableOpenPicker" | "disableMaskedInput" | "getOpenDialogAriaText" | "onClose" | "onAccept" | "autoOk" | "onOpen" | "showToolbar" | "ToolbarComponent"> & ExportedDateRangePickerInputProps & Pick<import("../wrappers/ResponsiveWrapper").ResponsiveWrapperProps, "displayStaticWrapperAs" | "DialogProps" | "okText" | "cancelText" | "clearText" | "todayText" | "clearable" | "showTodayButton" | "showTabs" | "wider" | "PopoverProps" | "PopperProps" | "TransitionComponent" | "desktopModeMediaQuery"> & React.RefAttributes<HTMLDivElement>>;
export declare type DesktopDateRangePickerProps = React.ComponentProps<typeof DesktopDateRangePicker>;
export declare const MobileDateRangePicker: React.ForwardRefExoticComponent<BaseDateRangePickerProps & Pick<import("../Picker/SharedPickerProps").AllSharedPickerProps<RangeInput, DateRangeType>, "label" | "mask" | "dateAdapter" | "value" | "className" | "onChange" | "open" | "disabled" | "orientation" | "readOnly" | "toolbarFormat" | "toolbarPlaceholder" | "toolbarTitle" | "InputProps" | "inputFormat" | "ignoreInvalidInputs" | "openPickerIcon" | "acceptRegex" | "InputAdornmentProps" | "OpenPickerButtonProps" | "rifmFormatter" | "disableOpenPicker" | "disableMaskedInput" | "getOpenDialogAriaText" | "onClose" | "onAccept" | "autoOk" | "onOpen" | "showToolbar" | "ToolbarComponent"> & ExportedDateRangePickerInputProps & Pick<import("../wrappers/ResponsiveWrapper").ResponsiveWrapperProps, "displayStaticWrapperAs" | "DialogProps" | "okText" | "cancelText" | "clearText" | "todayText" | "clearable" | "showTodayButton" | "showTabs" | "wider" | "PopoverProps" | "PopperProps" | "TransitionComponent" | "desktopModeMediaQuery"> & React.RefAttributes<HTMLDivElement>>;
export declare type MobileDateRangePickerProps = React.ComponentProps<typeof MobileDateRangePicker>;
export declare const StaticDateRangePicker: React.ForwardRefExoticComponent<BaseDateRangePickerProps & Pick<import("../Picker/SharedPickerProps").AllSharedPickerProps<RangeInput, DateRangeType>, "label" | "mask" | "dateAdapter" | "value" | "className" | "onChange" | "open" | "disabled" | "orientation" | "readOnly" | "toolbarFormat" | "toolbarPlaceholder" | "toolbarTitle" | "InputProps" | "inputFormat" | "ignoreInvalidInputs" | "openPickerIcon" | "acceptRegex" | "InputAdornmentProps" | "OpenPickerButtonProps" | "rifmFormatter" | "disableOpenPicker" | "disableMaskedInput" | "getOpenDialogAriaText" | "onClose" | "onAccept" | "autoOk" | "onOpen" | "showToolbar" | "ToolbarComponent"> & ExportedDateRangePickerInputProps & import("../wrappers/StaticWrapper").StaticWrapperProps & React.RefAttributes<HTMLDivElement>>;
export declare type StaticDateRangePickerProps = React.ComponentProps<typeof StaticDateRangePicker>;
export { DateRangeDelimiter } from './DateRangeDelimiter';
